OrderOfThePorcupine/ProjectPorcupine

- README.md
Our first PR :P.  Just removes the notice of moving since this is the moved project.  Also updates the passing thing to match this repository.
> [Small] Remove the notice of moving project

- Assets/Scripts/Localization/LocalizationDownloader.cs
Moves Localization into OrderOfThePorcupine/Localization, a repo that the organization can directly control and add collaborators to.
closes #52
> Use official localization repo

- Assets/Resources/Shaders/DepthShading.shader
- Assets/Resources/Shaders/Sprites-ColorSwap.shader
- Assets/Scripts/State/HaulState.cs
- Assets/StreamingAssets/CSharp/SettingsMenuFunctions.cs
Just a few here and there bits.  Found a leftover `profiler.endSample` and a weird variable loop that was wrong.
> [Small] Hotfix Patches 2

- Scripts/Contributor_Name_List.py
Just fixes the incorrect travis links.  Nothing else easy peasy.
> [Small Hotfix] Fix Incorrect travis links

- .travis.yml
- Scripts/bintray.json.erb
- Scripts/travis.sh
See #51 for the related discussion.
@koosemose To retrigger the cron-run (without waiting for a week) just delete the old job and create a new one.
PS: Should I rebase before merge or will you do it?
> Fix PR#51 Bugs

- Assets/Resources/UI/SettingsMenu/SettingsMenu.prefab
- Assets/Scripts/UI/InGameUI/PerformanceHUD/BasePerformanceHUDElement.cs
- Assets/Scripts/UI/InGameUI/PerformanceHUD/PerformanceGroup.cs
- Assets/Scripts/UI/InGameUI/PerformanceHUD/PerformanceHUDManager.cs
- Assets/Scripts/UI/InGameUI/SettingsMenu/BaseSettingsElement.cs
- Assets/Scripts/UI/InGameUI/SettingsMenu/SettingsMenu.cs
- Assets/Scripts/UI/InGameUI/SettingsMenu/SettingsOption.cs
- Assets/Scripts/UI/InGameUI/UIElements/UIClassData.cs
- Assets/Scripts/UI/InGameUI/UIElements/UIClassData.cs.meta
- Assets/StreamingAssets/Data/PerformanceHUDComponentGroups.xml
This just introduces the 'UIClassData' class which holds the class name and parameter data to make it more clear (especially in PerformanceHUD) that the list of parameters isn't representative of 'one class' but rather multiple (as in each class gets its own parameter).  To make it consistent I also implemented it in settings menu (makes name referencing a little longer), this only affects the XML reading.  Also it fixes a minor bug in settings menu (one of the sliders was the opposite way of the rest of our sliders, it was scroll up to go down a weird thing that was due to me needing at one point to 'flip' around the elements that isn't needed anymore).
> Compartmentalised UI Classes 

- Assets/Scripts/Controllers/InputOutput/BuildModeController.cs
- Assets/Scripts/Controllers/Sprites/JobSpriteController.cs
- Assets/Scripts/Models/Area/TemperatureDiffusion.cs
- Assets/Scripts/Models/Buildable/TileType.cs
- Assets/Scripts/Models/Job/Job.cs
- Assets/Scripts/Models/OrderActions/ChangeTileType.cs
- Assets/Scripts/Models/OrderActions/ChangeTileType.cs.meta
- Assets/Scripts/Models/OrderActions/OrderAction.cs
- Assets/Scripts/UI/InGameUI/MenuLeft/ConstructionMenu.cs
- Assets/StreamingAssets/Data/Tiles.xml
The name is mostly due to both Tile and TileType being used up by other classes so have to settle for more of a longer name.  Anyways just adds this in, not tested yet but 'should work'.  While there are formatting changes to xml (spacing) we are moving to JSON, so in reality they aren't really a concern.  
Anyways I'll test it sometime soon.
> Added ChangeTileType Build Action

- Assets/StreamingAssets/LUA/Overlay.lua
- Assets/StreamingAssets/MainMenu/Audio.meta
- Assets/StreamingAssets/Shared/Images.meta
- Assets/_Scenes_/_World.unity
Overlays not working properly
Updates old lua scripts to work with the new room atmosphere system
> Fixing overlays

- Assets/Editor/UnitTests/Models/Functions/LuaFunctionsTest.cs
- Assets/Editor/UnitTests/Models/Power/PowerGridTest.cs
- Assets/Editor/UnitTests/Models/Power/PowerNetworkTest.cs
- Assets/Editor/UnitTests/Utilities/DuplicateKeyComparerTest.cs
- Assets/Editor/UnitTests/Utilities/ModUtilsTest.cs
- Assets/Resources/Shaders/DepthShading.shader
- Assets/Resources/Shaders/Sprites-ColorSwap.shader
- Assets/Scripts/UI/InGameUI/MenuLeft/ConstructionMenu.cs
- Assets/Scripts/UI/InGameUI/MenuLeft/MenuLeft.cs
- Assets/Scripts/UI/InGameUI/MenuLeft/OrderMenu.cs
- Assets/StreamingAssets/MainMenu/Audio.meta
- Assets/StreamingAssets/Shared/Images.meta
- CONTRIBUTING.md
- README.md
Brings the project to Unity 5.6.1p2, this took quite a while since I had to wait till they fixed a bug that broke every single dropdown and then I went on a break, regardless here it is.
> [Upgrade] Unity 5.6

- CONTRIBUTING.md
> Update Localization link in CONTRIBUTING.md

- Assets/Scripts/UI/DialogBox/JobList/DialogBoxJobList.cs
Fixes a number typo inside the DialogBoxJobList class
> Dialogbox worktab typo

- Assets/Editor/UnitTests/Models/Functions/LuaFunctionsTest.cs
- Assets/Editor/UnitTests/Models/OrderActionTest.cs
As the title says.  Updates xml to json for the tests and fixes the lua one breaking if the lua channel was ever 'off', by saving the state turning it on then resetting the state.
> Fixed unit tests

- Assets/Scripts/Models/Area/World.cs
> Changed a log message to run inside the custom UnityDebugger

- Assets/Scripts/Models/InputOutput/ModsManager.cs
Inverted loops so that it only processes files it needs
> Rewrote prototype loading to only process files it actualy needs

- Assets/Editor/UnitTests/Controllers/HeadlineGeneratorTest.cs
- Assets/Editor/UnitTests/Models/SchedulerEditorTest.cs
- Assets/Editor/UnitTests/Mods.meta
- Assets/Editor/UnitTests/Mods/ModTester.cs
- Assets/Editor/UnitTests/Mods/ModTester.cs.meta
- Assets/Scripts/Controllers/MainMenuController.cs
- Assets/Scripts/Controllers/WorldController.cs
- Assets/Scripts/Models/Character/CharacterNameManager.cs
- Assets/Scripts/Models/Functions/FunctionsManager.cs
- Assets/Scripts/Models/InputOutput/AudioManager.cs
- Assets/Scripts/Models/InputOutput/ModsManager.cs
- Assets/Scripts/Models/InputOutput/SpriteManager.cs
- Assets/Scripts/Models/Prototypes/PrototypeManager.cs
This is the start of a system to verify mods that are checked in to make sure they are good. This will verify that the mods all load correctly, preventing Lua code from being checked in that has an error. I have verified with a bad Lua script it will fail the unit test.
> Unit testing mods, starting with just verifying the syntax.

- Assets/_Scenes_/_World.unity
The material was not properly saved. Somehow passed all unit tests. This fixes that.
> Line material was not included, should be.

- Assets/Editor/UnitTests/Controllers/HeadlineGeneratorTest.cs
- Assets/Editor/UnitTests/Models/SchedulerEditorTest.cs
This is a start of the project to get rid of all XML code.
> Updates Unit Tests to test JSON code.

- Assets/Scripts/Localization/LocalizationDownloader.cs
- Assets/Scripts/Localization/LocalizationTable.cs
Hotfix for an issue with updating the config.json file. It turns out that the file wasn't updating correctly, causing some issues sometimes.
> Correctly updates the config.json file

- Assets/Scripts/Models/Buildable/Components/Visuals.cs
- Assets/Scripts/Models/Buildable/Components/Workshop.cs
- Assets/Scripts/Models/Job/JobQueue.cs
- Assets/Scripts/UI/VisualPath.cs
- Assets/StreamingAssets/Data/Prototypes/Furniture.json
- Assets/StreamingAssets/Images/Furniture/small_landing_pad.json
- Assets/StreamingAssets/LUA/Furniture.lua
Played the game for a bit this morning, found a lot of outright bugs, mostly in the configuration files. Fixed those, and adding a bit of code to assist in debugging some other issues that have been seen as well. Changed some errors to warnings that were getting to be a bit verbose.
> Small bug fixes

- Assets/Scripts/Localization/LocalizationTable.cs
- Assets/StreamingAssets/Data/Prototypes/Furniture.json
- Assets/StreamingAssets/Data/Prototypes/Utility.json
- Assets/StreamingAssets/Localization/en_US.lang
I'm trying to catch some of the missing localization variables.
> Localization improvements

- Assets/Resources/UI/TimeScale.prefab
- Assets/Scripts/Models/Time/TimeScaleUpdater.cs
Just fixes it so there isn't a bit at the end.  Also fixes the colours a bit.
> Fixes to time scale

- Assets/Scripts/Controllers/InputOutput/BuildModeController.cs
Something that snuck by when upgrading the mouse handlers.
> Right clicking in build mode brings you out of buildmode

- Assets/Scripts/UI/Overlay/OverlayMap.cs
There was a small warning that both an image and text were added to the same item. I cleaned that up, and overall made the code a bit better and faster.
> Better practice for manually specified components.

- Assets/Scripts/Controllers/InputOutput/BuildModeController.cs
- Assets/Scripts/Localization/LocalizationTable.cs
- Assets/Scripts/Localization/TextLocalizer.cs
- Assets/Scripts/Models/Area/RoomBehavior.cs
- Assets/Scripts/Models/Buildable/Components/BuildableComponent.cs
- Assets/Scripts/Models/Buildable/Furniture.cs
- Assets/Scripts/Models/Buildable/Tile.cs
- Assets/Scripts/Models/Buildable/Utility.cs
- Assets/Scripts/Models/Character/Character.cs
- Assets/Scripts/Models/ContextMenu/ContextMenuAction.cs
- Assets/Scripts/Models/Inventory/Inventory.cs
- Assets/Scripts/Models/Job/JobQueue.cs
- Assets/Scripts/UI/ContextMenu/ContextMenuItem.cs
- Assets/StreamingAssets/Data/Prototypes/Furniture.json
- Assets/StreamingAssets/Data/Prototypes/Utility.json
- Assets/StreamingAssets/Localization/en_US.lang
More missing localization stuff, and improved some tool tips to get the right value instead of falsely assuming the key was correct.
I also demoted a few logwarnings, in my mind that should be used for something that the game can recover from, but isn't good, like missing localizations, not you can't find stuff to continue working. That made finding the localization missing much easier.
> Localization fixes

- Assets/Resources/UI/VisualPath.prefab
- Assets/Resources/UI/VisualPath.prefab.meta
- Assets/Scripts/Controllers/Sprites/CharacterSpriteController.cs
- Assets/Scripts/Models/Character/Character.cs
- Assets/Scripts/State/MoveState.cs
- Assets/Scripts/UI/VisualPath.cs
An error was reporting with the Visual Path. When looking in to it, I decided to switch it to use the much more extensible LineRenderer. It seems to be in good working order now!
> Simplier, more extensible Visual Path, without errors

- Assets/Scripts/Localization/LocalizationTable.cs
- Assets/Scripts/Models/Buildable/Furniture.cs
- Assets/Scripts/UI/InGameUI/MenuLeft/OrderMenu.cs
- Assets/StreamingAssets/Data/Prototypes/Furniture.json
- Assets/StreamingAssets/Localization/en_US.lang
This allows for more complex localization to be done, allowing fewer tags to be required, and overall be more stable.
> Iterative Localization- Allows {1} {2}, loc_tag_1, loc_tag_2 to give something meaningful.

- Assets/Resources/UI/Cursors/Ship.png.meta
- Assets/Scripts/UI/Mouse/MouseCursor.cs
This reverts the old fix and now just updates the import settings as per @NogginBops 's suggestion (thanks for that by the way!).
> Fix cursor properly

- Assets/Editor/UnitTests/Models/BuildableComponentTest.cs
- Assets/Scripts/Models/Buildable/Components/BuildableComponent.cs
- Assets/Scripts/Models/Buildable/Components/FluidConnection.cs
- Assets/Scripts/Models/Buildable/Components/GasConnection.cs
- Assets/Scripts/Models/Buildable/Components/PowerConnection.cs
- Assets/Scripts/Models/Buildable/Components/Visuals.cs
- Assets/Scripts/Models/Buildable/Components/Workshop.cs
- Assets/Scripts/Models/Buildable/Furniture.cs
All BuildableComponents now have a validation script where we can put in any kind of issues we find that would lead to an invalid component. This can be used to make debugger easier for issues such as #126. This will find the problem in #126.
> Validation of BuildableComponents

- Assets/Scripts/Controllers/InputOutput/BuildModeController.cs
- Assets/Scripts/Models/Area/Room.cs
- Assets/Scripts/Models/Buildable/BuildableJobs.cs
- Assets/Scripts/Models/Buildable/Furniture.cs
- Assets/Scripts/Models/Job/JobManager.cs
- Assets/Scripts/Models/OrderActions/Build.cs
- Assets/Scripts/Models/OrderActions/ChangeTileType.cs
- Assets/Scripts/Models/OrderActions/Deconstruct.cs
- Assets/Scripts/Models/OrderActions/Mine.cs
- Assets/Scripts/Models/OrderActions/Uninstall.cs
- Assets/Scripts/UtilityNetwork/Connection.cs
More removing of unused XML imports.
> Removes more unused XML references, unneeded imports

- Assets/Scripts/UtilityNetwork/Connection.cs
Removing some variables that aren't touched and are private static, changed double to float where a float will do more then adequately.
> Removed dead variables and simplified.

- Assets/Editor/UnitTests/Models/JobTest.cs
- Assets/Editor/UnitTests/Models/JobTest.cs.meta
- Assets/Scripts/Controllers/InputOutput/BuildModeController.cs
- Assets/Scripts/Models/Buildable/Components/Workshop.cs
- Assets/Scripts/Models/Character/Character.cs
- Assets/Scripts/Models/InputOutput/ModsManager.cs
- Assets/Scripts/Models/Job/Job.cs
- Assets/Scripts/Models/Job/JobCategory.cs
- Assets/Scripts/Models/Job/JobCategory.cs.meta
- Assets/Scripts/Models/OrderActions/Build.cs
- Assets/Scripts/Models/OrderActions/ChangeTileType.cs
- Assets/Scripts/Models/OrderActions/Deconstruct.cs
- Assets/Scripts/Models/OrderActions/Mine.cs
- Assets/Scripts/Models/OrderActions/OrderAction.cs
- Assets/Scripts/Models/OrderActions/Uninstall.cs
- Assets/Scripts/Models/Prototypes/PrototypeManager.cs
- Assets/Scripts/Models/Prototypes/PrototypeMap.cs
- Assets/Scripts/State/NeedState.cs
- Assets/Scripts/Utilities/MathUtilities.cs
- Assets/StreamingAssets/Data/Prototypes/Jobs.json
- Assets/StreamingAssets/Data/Prototypes/Jobs.json.meta
- Assets/StreamingAssets/Data/Prototypes/Quest.json
- Assets/StreamingAssets/LUA/Furniture.lua
Adding job categories, which can be defined in .json. Added some error code to made debugging easier. All Jobs have a specified category.
Still to be done, in this PR or another:
1. Characters- How should we add priorities for each character? 
2. Set up the JobManager to use the Job Proirities and categories.
> Job Categories

- Assets/Scripts/Controllers/Sprites/JobSpriteController.cs
- Assets/Scripts/Models/Job/JobManager.cs
Continuing to work on a new job system, this new version now supports character priorities. Distance is not yet factored in.
> Jobs now queued by job type.

- Assets/Editor/UnitTests/Models/JobTest.cs
- Assets/Scripts/Controllers/InputOutput/BuildModeController.cs
- Assets/Scripts/Models/Job/JobManager.cs
- Assets/Scripts/Pathfinding/Path_AStar.cs
- Assets/Scripts/Pathfinding/Pathfinder.cs
- Assets/Scripts/Pathfinding/PathfindingPriorityQueue.cs
These two changes should allow us a better way to find the best path among many, requiring less full pathfinding and having the ability to get the distance quickly after pathfinding.
> JobManager assigns the closest job of the highest priority

- Assets/Scripts/Models/Inventory/InventoryManager.cs
- Assets/Scripts/Models/Job/Job.cs
Wasn't removing jobs from the queue when the job was unsuspended. Would occasionally lead to some jobs not being resumed. Did a test and verified that the jobs correctly resume after these changes.
> Improving job unsuspension

- Assets/StreamingAssets/Data/Prototypes/Furniture.json
It has been driving me crazy for a while that the Raw Copper Ore and Copper Smelting didn't show up in the same place. This addresses that critical issue!
> Copper Smelting and Raw Copper Ore now in same order.

- Assets/Scripts/Models/Buildable/Tile.cs
Caches the pathfinding cost, from profiling it should gain about 20% performance boost to pathfinding long distances.
> Cache pathfinding cost

- Assets/Scripts/Models/Job/Job.cs
- Assets/Scripts/State/IdleState.cs
Cleaned up a bit of code in Job and IdleState.
> Cleaned up job, idle code.

- Assets/Scripts/UI/InGameUI/GameMenu/GameMenuController.cs
- Assets/Scripts/UI/InGameUI/MenuLeft/ConstructionMenu.cs
- Assets/Scripts/UI/InGameUI/MenuLeft/MenuLeft.cs
- Assets/Scripts/UI/InGameUI/MenuLeft/OrderMenu.cs
Partially addresses #168
Currently menu's name doesn't equal to the opened menu's name(in method). I think, Action method cannot get actual value when currently menu set in OpenMenu(find's menu with object name) some reason. I tried to set currently menu in the menubutton action methods and it worked. Since I changed OpenMenu with OpenCurrentMenu.
> Fixes clicking on the lower buttons twice issue

- Assets/Resources/UI/Components/ContextMenuItem.prefab
- Assets/Resources/UI/ContextMenu.prefab
- Assets/Scripts/Models/Buildable/Components/GasConnection.cs
- Assets/Scripts/UI/ContextMenu/ContextMenu.cs
- Assets/_Scenes_/_World.unity
- ProjectSettings/ProjectSettings.asset
A sharper, cleaner context menu.
Fixes #219
> Context menu dialog improvements

- Assets/StreamingAssets/LUA/Furniture.lua
As the title says fixes it by changing the comparisons
> Fixed neq comparisons (!= to ~=) in `Furniture.lua`

- Assets/Editor/UnitTests/Models/JobTest.cs
- Assets/Editor/UnitTests/Mods/ModTester.cs
Cleaning up properly after mod testing, fewer setup calls made for job testing.
> Clean up after mod testing, fewer setup calls.

- Assets/StreamingAssets/LUA/RoomBehavior.lua
- Assets/StreamingAssets/WorldGen/DefaultStartArea.sav
Partially Completes #240.
Changes air pumps to vents (I presume that was the intention that the air goes both ways rather than just one way).
Removes all the hard coding of parameters (except for open/closeness since that makes sense, don't want to flush everyone out upon load).
Also fixes room behavior.lua for airlocks.
> Fixes to default save area

- Assets/Scripts/Controllers/Sprites/FurnitureSpriteController.cs
- Assets/Scripts/Controllers/Sprites/TileSpriteController.cs
- Assets/Scripts/Models/Area/World.cs
- Assets/Scripts/Models/Buildable/Furniture.cs
- Assets/Scripts/Models/Buildable/Tile.cs
- Assets/Scripts/Models/InputOutput/SpriteManager.cs
- Assets/Scripts/Models/Job/JobManager.cs
- Assets/Scripts/Pathfinding/Path_AStar.cs
- Assets/Scripts/Pathfinding/Pathfinder.cs
- Assets/Scripts/Pathfinding/RoomPath_AStar.cs
#256 with RoomPathing rather than cycling through all nodes.
> Pr/256 with RoomPath

- Assets/Scripts/Controllers/Sprites/FurnitureSpriteController.cs
- Assets/Scripts/Controllers/Sprites/TileSpriteController.cs
- Assets/Scripts/Models/Area/World.cs
- Assets/Scripts/Models/Buildable/Furniture.cs
- Assets/Scripts/Models/Buildable/Tile.cs
- Assets/Scripts/Models/InputOutput/SpriteManager.cs
- Assets/Scripts/Models/Inventory/InventoryManager.cs
- Assets/Scripts/Models/Job/Job.cs
- Assets/Scripts/Models/Job/JobManager.cs
- Assets/Scripts/Pathfinding/Path_AStar.cs
- Assets/Scripts/Pathfinding/Pathfinder.cs
- Assets/Scripts/Pathfinding/RoomPath_AStar.cs
- Assets/Scripts/State/HaulState.cs
Starts a preliminary fog of war, does room pathing. The Fog of war isn't perfect yet, but it does what I need it to do, which is help determine if a tile can be reached easily.
> Room path checking and Fog of war

- Assets/Scripts/Models/Job/Job.cs
- Assets/Scripts/Pathfinding/Pathfinder.cs
Uses a hashset, which is better optimized for such operations.
> Using a hash set, should slightly improve performance.

- Assets/Editor/UnitTests/Models/Area/WorldGeneratorTest.cs
- Assets/Scripts/Controllers/SceneController.cs
- Assets/Scripts/Models/Area/WorldGenerator.cs
- Assets/Scripts/Models/OrderActions/Deconstruct.cs
- Assets/Scripts/UI/DialogBox/DialogBoxNewGame.cs
- Assets/StreamingAssets/WorldGen/default.json
- Assets/StreamingAssets/WorldGen/default.json.meta
- Assets/StreamingAssets/WorldGen/empty.json
- Assets/StreamingAssets/WorldGen/empty.json.meta
Converted the world generation to JSON, including unit tests, and removed the ability to load in XML. Looks good so far to me!
> World Generation conversion to JSON

- Assets/Scripts/Controllers/Sprites/CharacterSpriteController.cs
- Assets/Scripts/Controllers/WorldController.cs
- Assets/Scripts/Localization/LocalizationData.cs
- Assets/Scripts/Localization/LocalizationDownloader.cs
- Assets/Scripts/Models/Buildable/Furniture.cs
- Assets/Scripts/Models/Functions/Parameter.cs
- Assets/Scripts/Models/InputOutput/AudioManager.cs
- Assets/Scripts/Models/Keyboard/KeyboardManager.cs
- Assets/Scripts/UI/InGameUI/DevConsole/DevConsole.cs
- Assets/Scripts/UI/InGameUI/SettingsMenu/SettingsCategory.cs
Changes some comments to no longer reference XML.
> Removes XML references from code.

- Assets/Resources/UI/MenuLeft/ConstructionMenu.prefab
- Assets/Scripts/UI/Animation/MenuAnimation.cs
- Assets/Scripts/UI/Animation/MenuAnimation.cs.meta
- Assets/Scripts/UI/Animation/SlideAnimation.cs
- Assets/Scripts/UI/Animation/SlideDirection.cs
- Assets/Scripts/UI/Animation/SlideDirection.cs.meta
- Assets/Scripts/UI/InGameUI/GameMenu/GameMenu.cs
- Assets/Scripts/UI/InGameUI/GameMenu/GameMenu.cs.meta
- Assets/Scripts/UI/InGameUI/MenuLeft/ConstructionMenu.cs
- Assets/Scripts/UI/InGameUI/MenuLeft/MenuLeft.cs
- Assets/Scripts/UI/InGameUI/MenuLeft/OrderMenu.cs
* MenuAnimation abstract class added for GameMenu implementation.
* SlideAnimation direction support added. ![slideanimation](https://user-images.githubusercontent.com/8862032/53342643-85055780-391f-11e9-9c70-edb12b4a8422.PNG)
* GameMenu abstract class added for implementing MenuAnimation without code duplication.
> GameMenu improvements.
