Assets/StreamingAssets/CSharp/SettingsMenuFunctions.cs

With moving projects sometimes errors pop up and this one seems to be with the LUA thing, I must have moved over the LUA to handle the dev mode without removing it in C# then removed just the class but not the function call.  This removes that function call.  Every works after this.

[Small] [Bug Fix] HotFix

---

Assets/Scripts/Models/Buildable/Furniture.cs
Assets/Scripts/Models/DialogBoxInformation/DialogButton.cs
Assets/Scripts/Models/Events/EventAction.cs
Assets/Scripts/Models/Functions/CSharpFunctions.cs
Assets/Scripts/Models/Functions/Functions.cs
Assets/Scripts/Models/Functions/LuaFunctions.cs

From me and koose having a look at the code we have both decided that a major problem is Moonsharp allocating tons of GC, at one point we may even want to hold onto the memory and do our own allocation if it really gets bad.  There are alternative ways like hardwiring which I'm also looking into.  
This aims to alleviate some of those problems.  It does a ton of work for furniture, and basically everything runs in the GameController update (about 70% of things) runs on less than 2kb/cycle (excluding Moonsharp).  However Moonsharp is using about 78kb/cycle (both from my profiling and their own profiler logs).  This is on a low, on highs it can go up to 120 with the whole thing running on less than 5kb/cycle for those high moments with the rest being Moonsharp.  
This patch helps a little …

[Performance Patch] Fixing GC problems

---

Assets/StreamingAssets/Data/Ships.xml

ships.xml was missing the xml header, and had the old tile types (different capitalization)

Add Xml Header on Ships and fix incorrect tile types

---

Assets/Scripts/Models/Trade/TraderPrototype.cs

TraderPrototype incorrectly passes valueBased parameter in the position of flipX parameter. This simply inserts `false` (the default value of flipX) into that position, pushing valueBased into the correct position.

Fix TraderPrototype Animation Creation

---

Assets/Scripts/Models/Trade/TraderPrototype.cs

Fixes #66 
Fixes bug where not set in xml causing fps of 0 to be passed (in TraderPrototype and Furniture)
Fixes bug where fps is being passed as delay (in TraderPrototype)
Still leaves the repetition of code in the various ways Animation is handled, and each thing that uses animation handling their own xml processing (giving the potential for future inconsistencies and bugs due to multiple classes reimplementing the same behavior), but this is a more significant issue, so I will raise it in a separate issue, rather than letting these simpler bugfixes wait while a more full solution is approached.

Fix TraderPrototype Animation Creation ( #66 )

---

Assets/Scripts/UI/InGameUI/SettingsMenu/SettingsOption.cs

SettingsOption in its current form doesn't read in the closing tag, leaving a closing tag for the category to read, which the xmlReader doesn't recognize as a closing tag. Slightly changing SettingsOption to use ReadSubTree, lets it properly close the tag, rather the Option is a self closing tag or a normal tag with a separate closing tag.

Fix SettingsOption creating phantom Options

---

README.md
Scripts/bintray.json.erb
Scripts/build.sh

Zip paths for the prebuilt binaries are a little too deep (starting from travis' current working directory, this instead changes the directory to a closer directory before zipping to create shallower directory paths.
This also changes the name to Prebuilt Binaries (with the accompanying changes to bintray), and adds the link to them to the Readme (language may need further review, but the general intent should remain the same).
I will delay merging this for a short time (a day or two at most) to allow time for people to review the wording around the added Weeklies section in the Readme, barring any extended discussion/debate on it.

Small tweaks to prebuilt binaries.

---

Assets/Scripts/Models/Character/Character.cs
Assets/Scripts/Models/Job/Need.cs
Assets/StreamingAssets/Data/Need.xml

Removes Name from Needs, as that is a relic of prelocalization, and only serves to cause confusion now.

Remove Need Name, switch to Type

---

Assets/Scripts/UI/Overlay/OverlayDescriptor.cs
Assets/StreamingAssets/Data/Overlay.xml

Min and Max are unused by overlays, and seemed to serve little point.

Remove Min/Max from overlay

---

.travis.yml
Scripts/bintray.json.erb
Scripts/build.sh

Fixes #88 (and probably #87 as not really the "latest" Windows Version was used. There is no point in debugging an 4 week old build)
As usual this can't really be tested so please @koosemose  review the code for obvious typos but other than that its merge and hope :cry:
Btw I didn't find any hint that the same names aren't allowed (other than the error message) I thought that the version (tag) is sufficient thats what I wanted. A new version of the same file(name) but I looked thorugh some other repos @ bintray and they all include the Version number in the filename.

Add BUILD_VERSION to files and set it globally in .travis.yml

---

Assets/Scripts/Controllers/WorldController.cs
Assets/_Scenes_/_World.unity

InventoryUI was broken by a recent commit (InventoryUI being the UI bit that shows the number of objects in a stack of Inventory).
This simply changes it back to a field and makes it private and tells Unity to serialize it (the only reason it was public previously was to serialize it, and it isn't used anywhere else, just to pass along to InventorySpriteManager).

Fix InventoryUI Prefab

---

Assets/Scripts/Models/Area/AtmosphereComponent.cs

Currently, gas does not move correctly, this shows both when joining rooms (deleting a wall between rooms) or in equalization (such as through doors or a vent). 
The cause is as each gas is moved, it does it based on the total to be moved and the ratio of that gas in the room, after the first gas is moved, the total amount in the room is changed (thus changing the ratio of the second gas in the room) but the total to move isn't changed, so when the second gas is moved, it has a higher than previous ratio of the total amount to move. This *may* also cause additional gas of the second (and further) type to be generated as well, though I haven't thoroughly tested this second issue, as fixing the first should fix the second should it exist.
Presently this is done with a second loop, setting …

Fix Gas Splitting

---

README.md

Updating the linked downloads to a recent security patch.
Initial security notification from Unity: https://np.reddit.com/r/Unity3D/comments/6ug0ig/security_notification_unity_editor/

Update download link to 5.6.3 Security patch

---

Scripts/test.sh

Command line option to set editor results file location was mistyped. I have no idea how it has ran properly up to this point.

Update build script

---

.gitignore

With the new version of visual studio 2017 some new files have to be ignored.  These are all the ones that I could find that seem to be the 'odd ones out' that are also relevant to us.

Fixes up gitignore

---

Scripts/Install/unity.sh

Hopefully this fixes it.  This just removes a download link that doesn't exist because it comes standard with the MacEditor (that is the UnitySetup-MacEditor Support).

Build Script Fix

---

README.md

I Registered the projectporcupine.com domain when there was talk for creating a dev blog, it has since expired so this reference to it should be removed.

Remove Expired Domain

---

Assets/Scripts/Controllers/GameController.cs
Assets/Scripts/Controllers/MainMenuController.cs
Assets/Scripts/Controllers/WorldController.cs
Assets/Scripts/Localization/LocalizationLoader.cs
Assets/Scripts/Models/Settings/Settings.cs
Assets/StreamingAssets/MainMenu/Audio.meta

Settings had a few bugs mainly to do with the order of loading the settings file.  It worked (honestly more like a miracle) that the order was fine in World but somehow the execution order wasn't in _MainMenu.  So this just fixes that, by removing the static load (which in actual fact didn't 'really' work unless the user had all the settings already) and moved a lot of the initialisation code from start to awake in `MainMenuController` for mods just so settings can load properly.  
When I redo GameController in #99 this will be nicer as right now it's a bandaid fix (well more like a bandage fix its more holistic), this won't effect anything but some weird side effects 'could' occur, though I did pretty intensive testing and they didn't.  And when #99 gets merged in eventually this …

[Fix] Settings Bugs

---

Assets/Scripts/UI/InGameUI/DevConsole/CommandTypes/InvokeCommand.cs

The Vector3 errors DevConsole keeps throwing
Rewrite the parser function for prototypes so that is is able to accept UnityEngine parameters

Fixed namespace searching for prototypes

---

Assets/Scripts/UI/InGameUI/DevConsole/CommandTypes/InvokeCommand.cs

There where a lot of warnings where InvokeCommand.cs could not find the types it needed.
This PR adds UnityEngine.CoreModule to the search where all of the missing types are located.

Fix a lot of warnings from InvokeCommand

---

Assets/Scripts/Localization/LocalizationData.cs
Assets/Scripts/Localization/LocalizationDownloader.cs
Assets/Scripts/Localization/LocalizationLoader.cs
Assets/Scripts/Localization/LocalizationTable.cs

This continues the path of getting XML data removed from the project. In this edition, we set the localization data to load a JSON file, and update said file upon completion.

Localization data switch from XML to JSON

---

Assets/Scripts/Localization/LocalizationData.cs

When I introduced the localization to JSON, I inadvertently created a Stack Overflow possibility. This fixes that.

Hot Fix: Prevent Stack Overflow on localization.

---

Assets/StreamingAssets/Data/Prototypes/Utility.json

Right now we don't have a way to make copper wiring. Let's not use it for something so basic. We can reevaluate this at a later date if needed.

Copper plates are available, copper wire isn't. Let's use copper plate

---

Assets/Scripts/UI/InGameUI/SettingsMenu/SettingsMenu.cs

Fixes #155 
I haven't been able to test this yet, but if one of you get the time before I do (I'll end up testing it tomorrow).
Currently do note that 'changes' means causing any element to update that could be toggling a switch on, then off again so it doesn't necessarily mean that you actually made changes but rather at minimum edited some of the values!
I'll probably also look at if I get the time actually telling the user what changes they have made i.e. something like;
```
Do you want to cancel
Changes Made:
- Resolution: Low -> High
- Sound Volume: 50 -> 55
Yes               No
```
And in doing that I would fix the issue of making changes (but really actually not making any, like changing a value to 80 then back to 50 for example).

#155 BugFix

---

Assets/Scripts/Controllers/InputOutput/BuildModeController.cs
Assets/Scripts/Controllers/InputOutput/MouseController.cs
Assets/Scripts/Models/Inventory/Inventory.cs
Assets/Scripts/UI/InGameUI/MenuLeft/MenuLeft.cs
Assets/StreamingAssets/CSharp/CommandFunctions.cs

As the title says, this is to go along with #177.  This makes the decision that BuildModeController is only ever an instance since it requires a world to exist and can't exist independently of that.

Removed references to BuildModeController.Instance

---

Assets/StreamingAssets/LUA/Need.lua

Fixed a typo in the LUA

---

Assets/Scripts/Controllers/Events/SpawnInventoryController.cs

It would cause the inventory to spawn with `0` items.
This was due to the call to SpawnInventory invalidating the inventory that we passed.

Fix issue with spawning inventory one after each other

---

Assets/Scripts/Models/Buildable/Furniture.cs
Assets/Scripts/Models/Buildable/Utility.cs
Assets/Scripts/Models/Inventory/Inventory.cs

Fixes #30 . Basically sets meaningful defaults for localization names to what is basically our schema for giving them names in the first place. I did test this out with Steel Wall, and it found the correct localization name. We could remove all of the default ones from the 3 files now if desired.

Localization defaults for furniture, utilities, and inventory

---

Assets/Scripts/Models/Area/AtmosphereComponent.cs

Fixes #196.
Basically what was happening is total gas was computed separately from the individual components. Due to floating point inaccuracies, sometimes the total gas could be less than 0. This should prevent that from happening.

Total Gas is updated as the sum of all gas components

---

Assets/Scripts/Models/Buildable/Components/Workshop.cs

Fixes #135 
Basically what is happening is there is no output for a water generator in the .json, as the outputs are utilities, not products. When it goes to check to see if there is any outputs, it crashes. This puts a check for that condition, and will return nothing if there is no outputs, allowing it to still function.

Fixes crash when no output stations and input runs out

---

Assets/Plugins/fmod.bundle.meta

This is mainly needed to not only be consistent but also allow us to test in play mode.
It used to only work in the editor and standalone but now it can load during playmode

Update fmod meta data to match the rest of the plugins

---

Assets/Scripts/Utilities/MathUtilities.cs

This is leading to inconsistent behavior sometimes in determining if there is no atmosphere in a room.

For floats, should check float.epsilon, not double.epsilon.

---

Assets/Scripts/UI/InGameUI/SettingsMenu/SettingsMenu.cs

This could occur for example if you can't show the cancel box (which arguably can't occur in any of our scenes) but could also occur occasionally if you pressed cancel without selecting changes (slipped through out testing).  Also clears the current category and the change tracker in the case where it can't show the cancel box.

Fix to occasional issue with settings menu not correctly clearing modality

---

README.md

This could act as a deterrence and isn't really true anymore

I think it is time to remove the notice of `delayed development`

---

Assets/Scripts/Localization/LocalizationTable.cs
Assets/Scripts/Models/Inventory/Inventory.cs

Formatting localization could sometimes fail if the wrong number of arguments were present. This now no longer outright fails, and also fixes one of the instances of missing localization arguments.

Fixed localization bug

---

Assets/Scripts/Controllers/Sprites/TileSpriteController.cs
Assets/Scripts/Models/InputOutput/SpriteManager.cs

This changes the TileSpriteController to use tilemaps instead of using individual GameObjects.
This makes startup a lot faster as we don't create thousands of GameObjects and add conponents thousands of times.

Made TileSpriteController use Tilemap

---

Assets/Scripts/Controllers/InputOutput/MouseController.cs

A bug existed to only show the 0 level, due to only using the 2-d mouse index. Changed this to use the z-level correctly, and it now works!

Context menus now show up for the right Z-level.

---

Assets/Scripts/Models/Buildable/Components/GasConnection.cs

Fixes #229 
A gas generator, or anything requiring gas, shouldn't function outside.

Gas connections will not function outside.

---

Assets/Scripts/UI/InGameUI/SettingsMenu/SettingsMenu.cs

Exit is now a private function for closing the menu.
We load all the changes made in the current heading before cancelling to make sure the user hasn't made any changes before not showing the popup.

Settings menu cancel improvement and cleanup of exit

---

Assets/Scripts/Models/Buildable/Tile.cs
Assets/Scripts/Models/Job/Job.cs
Assets/Scripts/Models/Job/JobManager.cs

This will check to see if a job can be reached before pathing to it, making mining large patches much less annoying.
Still won't work perfectly if in the middle of an unreachable room, but that will come with a future upgrade.

Suspends jobs if they can't be reached.

---

Assets/Scripts/UI/DialogBox/DialogBox.cs
Assets/Scripts/UI/DialogBox/DialogBoxManager.cs
Assets/Scripts/UI/DialogBox/JobList/DialogBoxJobList.cs
Assets/Scripts/UI/InGameUI/GameMenu/GameMenuController.cs
Assets/Scripts/UI/InGameUI/GameMenu/GameMenuManager.cs
Assets/Scripts/UI/InGameUI/MenuLeft/MenuLeft.cs

Makes it so that all menus in the lower bar can be closed again by pressing the button that opened it again.

[Conflicted] Make all lower-bar menus closable by pressing the button that opened them

---

Assets/Scripts/Controllers/InputOutput/BuildModeController.cs
Assets/Scripts/Models/Buildable/BuildableJobs.cs
Assets/Scripts/Models/Buildable/UtilityManager.cs
Assets/Scripts/Models/Job/Job.cs
Assets/Scripts/State/JobState.cs

Cleans up a bit on where PendingBuildJobs is added to and removed from, also removed incorrect calls to CancelJob (was being called when the job was being paused), which should now allow jobs that have had some inventory delivered to them to be cancellable.

Fix pending build jobs
